import ReactDOM from 'react-dom/client';
import './index.css';

import { BrowserRouter } from 'react-router-dom';

import { Router } from './router';

// createRoot lets you create a root to display React components inside a browser DOM node.
// ReactDOM.createRoot(document.getElementById('root')!).render(
//   <React.StrictMode>
//     <App />
//   </React.StrictMode>,
// )

// hydrateRoot lets you display React components inside a browser DOM node whose HTML content was previously generated by react-dom/server.
ReactDOM.hydrateRoot(
  document.getElementById('root')!,
  <BrowserRouter>
    <Router />
  </BrowserRouter>
);
